#!/bin/bash

# Detect monitors
LAPTOP_MONITOR=$(xrandr | grep "eDP" | grep " connected" | awk '{print $1}')
EXTERNAL_MONITOR=$(xrandr | grep "HDMI" | grep " connected" | awk '{print $1}')

# Fallbacks if no monitors detected
if [[ -z "$LAPTOP_MONITOR" ]]; then
    LAPTOP_MONITOR="eDP-1"
fi
if [[ -z "$EXTERNAL_MONITOR" ]]; then
    EXTERNAL_MONITOR="HDMI-1"
fi

# Generate dynamic workspaces.conf
cat <<EOL > ~/dotfiles/i3/.config/i3/ws.conf
# This file is generated by gen_ws.sh do not edit manually edit workspaces.sh instead
set \$lpt_monitor "$LAPTOP_MONITOR"
set \$ext_monitor "$EXTERNAL_MONITOR"
EOL

# Append the contents of the existing workspaces.conf
cat ~/dotfiles/i3/.config/i3/workspaces.conf >> ~/dotfiles/i3/.config/i3/ws.conf
